### ISSUE TITLE
Update `README.md` to include relevant starter information.

### ISSUE THREAD

**Issue by elliottyoon** [hajowolfram/ScaDS_project#1]
The README.md claims to give directions for how to run the project, but only provides commands to perform necessary setup.
It might be beneficial to consider adding a few points detailing:
- what the project is used for, and
- how to use it once the dependencies / etc are installed.

**Comment by hajowolfram** [comment]
resolved https://github.com/hajowolfram/ScaDS_project/commit/93d69c31731cda01bfcca5e5593579f9f09d49a1
